const Gig = [
    {
        id: 1,
        heading: "Branding Design Guidelines",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 2,
        heading: "University Project Development",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 3,
        heading: "Social media posts Design",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 4,
        heading: "Independent Language Translator ",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        level: "Expert",
        category: "gigs",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 5,
        heading: "Independent Language Translator ",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 6,
        heading: "Independent Language Translator ",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 7,
        heading: "Independent Language Translator ",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "posted_gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 8,
        heading: "Independent Language Translator ",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "posted_gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 9,
        heading: "Independent Language Translator ",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "posted_gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 10,
        heading: "Independent Language Translator ",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "posted_gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 11,
        heading: "Independent Language Translator ",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "posted_gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
    {
        id: 12,
        heading: "Independent Language Translator ",
        date: "11/01/2023",
        months: "6 months",
        price: "7000ALA",
        category: "posted_gigs",
        level: "Expert",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris",
    },
]

export default Gig;